name: Release

on:
  push:
    tags: ['v*.*.*-custom']

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable

    - name: Setup MUSL
      if: matrix.os == 'ubuntu-latest'
      run: |
        rustup target add x86_64-unknown-linux-musl
        sudo apt-get -qq install musl-tools

    - name: Build
      run: make release

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: '*.tar.xz'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
